# Generated by Django 5.1.6 on 2025-02-26 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_author_book_author_obj_userbookstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_obj',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.author'),
        ),
    ]
