# Generated by Django 5.1.6 on 2025-02-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_userfollowauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_link', to='page.author'),
        ),
    ]
