# Generated by Django 5.1.6 on 2025-03-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_alter_book_category_alter_review_review_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTemplate',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='page.book')),
            ],
            bases=('page.book',),
        ),
    ]
