# Generated by Django 5.1.6 on 2025-03-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_booktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktemplate',
            name='template',
            field=models.BooleanField(default=True),
        ),
    ]
