# Generated by Django 5.1.6 on 2025-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_booktemplate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='BookTemplate',
        ),
    ]
