# Generated by Django 5.1.6 on 2025-03-12 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_author_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_template',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fantastyka', 'Fantastyka'), ('Science Fiction', 'Science Fiction'), ('Romans', 'Romans'), ('Thriller', 'Thriller'), ('Tajemnica', 'Tajemnica'), ('Kryminał', 'Kryminał'), ('Horror', 'Horror'), ('Biografia', 'Biografia'), ('Historia', 'Historia'), ('Manga', 'Manga'), ('Religia', 'Religia'), ('Komiks', 'Komiks'), ('Przygoda', 'Przygoda'), ('Psychologia', 'Psychologia'), ('Komedia', 'Komedia'), ('Dramat', 'Dramat'), ('Filozofia', 'Filozofia'), ('Naukowe', 'Naukowe')], max_length=50),
        ),
    ]
