# Generated by Django 5.1.6 on 2025-03-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
